name: remindly
region: nyc

# Backend Service (must come first for route priority)
services:
  - name: backend
    source_dir: backend
    github:
      repo: KoiralaSam/Remindly
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
        preserve_path_prefix: true
      - path: /ws
        preserve_path_prefix: true
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    # HTTPS is automatically enabled by App Platform for all routes
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: CORS_ORIGINS
        scope: RUN_TIME
        type: SECRET
      - key: APP_URL
        scope: RUN_TIME
        type: SECRET
      - key: SENDGRID_EMAIL_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SENDGRID_FROM_EMAIL
        scope: RUN_TIME
        type: SECRET
      - key: SENDGRID_FROM_NAME
        scope: RUN_TIME
        type: SECRET
      - key: AWS_ACCESS_KEY_ID
        scope: RUN_TIME
        type: SECRET
      - key: AWS_SECRET_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: AWS_REGION
        scope: RUN_TIME
        type: SECRET
      - key: AWS_S3_BUCKET
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET

  # Frontend Service
  - name: client
    source_dir: client
    github:
      repo: KoiralaSam/Remindly
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      # Use empty string for relative URLs since both services share the same domain in App Platform
      # The API paths already include /api prefix, so we just need the domain (empty = same domain)
      - key: VITE_API_BASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ""
    depends_on:
      - backend
# HTTPS Configuration
# App Platform automatically provides HTTPS for all routes
# To enable custom domain with HTTPS:
# 1. Go to App Platform dashboard → Settings → Domains
# 2. Add your custom domain
# 3. App Platform will automatically provision Let's Encrypt certificate
# 4. Update CORS_ORIGINS to include your custom domain
