-- +goose Up
-- +goose StatementBegin

CREATE TABLE auths (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    auth_uuid UUID NOT NULL DEFAULT gen_random_uuid()
);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE auths;
-- +goose StatementEnd
